name: Test pull request

on:
  pull_request:
    types:
      - opened
    branches:
      - "dependabot/**"
  workflow_dispatch:

jobs:
  build-gms-flavor-debug:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/daemon
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.android/build-cache
            ~/.android/cache
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK with Gradle
        run: ./gradlew assembleGmsDebug --parallel --build-cache --configuration-cache

      - name: Build debug bundle with Gradle
        run: ./gradlew bundleGmsDebug --parallel --build-cache --configuration-cache

  build-gms-flavor-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/daemon
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.android/build-cache
            ~/.android/cache
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release APK with Gradle
        run: ./gradlew assembleGmsRelease --parallel --build-cache --configuration-cache

      - name: Build release bundle with Gradle
        run: ./gradlew bundleGmsRelease --parallel --build-cache --configuration-cache
