name: Test pull request

on:
  pull_request:
    types:
      - opened
    branches:
      - "dependabot/**"
  workflow_dispatch:

jobs:
  build-gms-flavor-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK with Gradle
        run: ./gradlew assembleGmsDebug

      - name: Build debug bundle with Gradle
        run: ./gradlew bundleGmsDebug

  build-gms-flavor-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release APK with Gradle
        run: ./gradlew assembleGmsRelease

      - name: Build release bundle with Gradle
        run: ./gradlew bundleGmsRelease
